LEVEL_SELECT_OPTIONS:`gameLevel`randomiserMode`numShownInQueue`canHoldPieces`showGuidePiece`allowWallKicks`allowFloorKicks`play;
LEVEL_SELECT_TOGGLE_OPTIONS:`canHoldPieces`showGuidePiece`allowWallKicks`allowFloorKicks;

DEFAULT_GAME_LEVEL:0;
DEFAULT_RANDOMISER:`modern;
DEFAULT_NUM_SHOWN_IN_QUEUE:4;
DEFAULT_CAN_HOLD_PIECES:1b;
DEFAULT_SHOW_GUIDE:1b;
DEFAULT_ALLOW_WALL_KICKS:1b;
DEFAULT_ALLOW_FLOOR_KICKS:1b;
